// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuhdqxaiewdztzuxriho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aGRxeGFpZXdkenR6dXhyaWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTQ1NjcsImV4cCI6MjA2NTI3MDU2N30.T3EAHi3ayX_5MG93jr2n6HVXe_CLsEUh_udCfi441mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);